# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    # Test name: Untitled
    # Step # | name | target | value
    # 1 | open | /stock/brokertrace.aspx?bno=9268&no=6202 | 
    self.driver.get("https://histock.tw/stock/brokertrace.aspx?bno=9268&no=6202")
    # 2 | setWindowSize | 968x1020 | 
    self.driver.set_window_size(968, 1020)
    # 3 | click | id=login | 
    self.driver.find_element(By.ID, "login").click()
    # 4 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 5 | type | id=email | jona9639@gmail.com
    self.driver.find_element(By.ID, "email").send_keys("jona9639@gmail.com")
    # 6 | click | id=password | 
    self.driver.find_element(By.ID, "password").click()
    # 7 | type | id=password | jona789521456
    self.driver.find_element(By.ID, "password").send_keys("jona789521456")
    # 8 | click | id=bLogin | 
    self.driver.find_element(By.ID, "bLogin").click()
  
